export const SAVE_REQUEST = "SAVE_REQUEST";
export const SAVE_SUCCESS = "SAVE_SUCCESS";
export const SAVE_FAIL = "SAVE_FAIL";

export const All_EMAIL_REQUEST = "All_EMAIL_REQUEST";
export const All_EMAIL_SUCCESS = "All_EMAIL_SUCCESS";
export const All_EMAIL_FAIL = "All_EMAIL_FAIL";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
